const yokaiData = [
  { name: "アチャー", yomi: "あちゃー", alias: "Sigh-Durr" },
  { name: "枕返し", yomi: "まくらがえし", alias: "Flippit" },
  { name: "ぶようじん坊", yomi: "ぶようじんぼう", alias: "Pandle" },
  { name: "がらあきん坊", yomi: "がらあきんぼう", alias: "Undy" },
  { name: "さきがけの助", yomi: "さきがけのすけ", alias: "Tanbo" },
  { name: "ダラケ刀", yomi: "だらけとう", alias: "Cutta-nah" },
  { name: "ザンバラ刀", yomi: "ざんばらとう", alias: "Cutta-nah-nah" },
  { name: "ダララだんびら", yomi: "だららだんびら", alias: "Slacka-slash" },
  { name: "かたづ家来", yomi: "かたづけらい", alias: "Brushido" },
  { name: "アライ魔将", yomi: "あらいましょう", alias: "Washogun" },
  { name: "獅子まる", yomi: "ししまる", alias: "Lie-in" },
  { name: "万尾獅子", yomi: "まんおじし", alias: "Lie-in Heart" },
  { name: "おこ武者", yomi: "おこむしゃ", alias: "Hissfit" },
  { name: "くしゃ武者", yomi: "くしゃむしゃ", alias: "Zerberker" },
  { name: "なまはげ", yomi: "なまはげ", alias: "Snartle" },
  { name: "なまなまはげ", yomi: "なまなまはげ", alias: "Brutle" },
  { name: "ちからモチ", yomi: "ちからもち", alias: "Mochismo" },
  { name: "やきモチ", yomi: "やきもち", alias: "Minochi" },
  { name: "一瞬ボーイ", yomi: "いっしゅんぼーい", alias: "Minimoto" },
  { name: "寝ブタ（ねぶた）", yomi: "ねぶた", aliases: ["Slumberhog", "Snortlehog"] },
  { name: "ひつま武士", yomi: "ひつまぶし", alias: "Samureel" },
  { name: "ひまつ武士", yomi: "ひまつぶし", alias: "Time Keeler" },
  { name: "ダメジャー", yomi: "だめじゃー", alias: "Goofball" },
  { name: "ダメジャナイン", yomi: "だめじゃないん", alias: "Slugger" },
  { name: "カブトさん", yomi: "かぶとさん", alias: "Helmsman" },
  { name: "ゲンマ将軍", yomi: "げんましょうぐん", alias: "Reuknight" },
  { name: "黄泉ゲンスイ", yomi: "よみげんすい", alias: "Corptain" },
  { name: "おにぎり侍", yomi: "おにぎりざむらい", alias: "Slicenrice" },
  { name: "焼きおに斬り", yomi: "やきおにぎり", alias: "Flamurice" },
  { name: "あかなめ", yomi: "あかなめ", alias: "Tublappa" },
  { name: "総ナメ", yomi: "そうなめ", alias: "Lappinitup" },
  { name: "ガチン小僧", yomi: "がちんこぞう", alias: "El Gutso" },
  { name: "天下無僧", yomi: "てんかむそう", alias: "Gutso Grande" },
  { name: "泥田坊", yomi: "どろたぼう", alias: "Mudmunch" },
  { name: "ニクヤ鬼", yomi: "にくやき", alias: "BBQvil" },
  { name: "シラ切りスズメ", yomi: "しらきりすずめ", alias: "Liarbird" },
  { name: "ベンケイ", yomi: "べんけい", alias: "Benkei" },
  { name: "からくりベンケイ", yomi: "からくりべんけい", alias: "B3-NK1" },
  { name: "メラメライオン", yomi: "めらめらいおん", alias: "Blazion" },
  { name: "グラグライオン", yomi: "ぐらぐらいおん", alias: "Quaken" },
  { name: "とどろき獅子", yomi: "とどろきじし", alias: "Siro" },
  { name: "しょうブシ", yomi: "しょうぶし", alias: "Chansin" },
  { name: "まさむね", yomi: "まさむね", alias: "Sheen" },
  { name: "むらまさ", yomi: "むらまさ", alias: "Snee" },
  { name: "くさなぎ", yomi: "くさなぎ", alias: "Gleam" },
  { name: "フユニャン", yomi: "ふゆにゃん", alias: "Hovernyan" },
  { name: "妖怪ガッツK", yomi: "ようかいがっつけー", alias: "Moximous N" },
  { name: "妖怪ガッツF", yomi: "ようかいがっつえふ", alias: "Moximous K" },
  { name: "いばる〜ん", yomi: "いばるーん", alias: "Hot Air Buffoon" },
  { name: "やまと", yomi: "やまと", alias: "Sushiyama" },
  { name: "カブキ猿", yomi: "かぶきざる", alias: "Kapunki" },
  { name: "クワノ武士", yomi: "くわのぶし", alias: "Beetler" },
  { name: "クワガ大将", yomi: "くわがたいしょう", alias: "Beetall" },
  { name: "オオクワノ神", yomi: "おおくわのかみ", alias: "Cruncha" },
  { name: "マスクドニャーン", yomi: "ますくどにゃーん", alias: "Machonyan" },
  { name: "モモタロニャン", yomi: "ももたろにゃん", alias: "Momonyan" },
  { name: "ニャン騎士", yomi: "にゃんきし", alias: "Sir Nyansalot" },
  { name: "ブリー隊長", yomi: "ぶりーたいちょう", alias: "Sgt. Burly" },
  { name: "ブリー元帥", yomi: "ぶりーげんすい", alias: "Bison Burly" },
  { name: "鬼食い", yomi: "おにくい", alias: "Demuncher" },
  { name: "いのちとり", yomi: "いのちとり", alias: "Devourer" },
  { name: "ヒカリオロチ", yomi: "ひかりおろち", alias: "Illuminoct" },
  { name: "鬼蜘蛛", yomi: "おにぐも", alias: "Arachnevil" },
  { name: "ハンゾウ", yomi: "はんぞう", alias: "Shurikenny" },
  { name: "コタロウ", yomi: "こたろう", alias: "Nunchucky" },
  { name: "椿姫", yomi: "つばきひめ", alias: "Camellia" },
  { name: "さかさっ傘", yomi: "さかさっかさ", alias: "Brokenbrella"},
  { name: "化け草履", yomi: "ばけぞうり", alias: "Pittapatt"},
  { name: "パッカー", yomi: "ぱっかー", alias: "Zip Unlock"},
  { name: "口すべらし", yomi: "くちすべらし", alias: "Slippup"},
  { name: "ズルズルづる", yomi: "ずるずるづる", alias: "Snotsolong" },
{ name: "かぜカモ", yomi: "かぜかも", alias: "Duchoo" },
{ name: "つづかな僧", yomi: "つづかなそう", alias: "D'wanna" },
{ name: "やめたい師", yomi: "やめたいし", alias: "N'more" },
{ name: "もうせん和尚", yomi: "もうせんおしょう", alias: "Q'wit" },
{ name: "わすれん帽", yomi: "わすれんぼう", alias: "Wazzat" },
{ name: "メゾン・ドワスレ", yomi: "めぞんどわすれ", alias: "Houzzat" },
{ name: "ばか頭巾", yomi: "ばかずきん", alias: "Dummkap" },
{ name: "そらミミズク", yomi: "そらみみずく", alias: "Who-Me" },
{ name: "じごくミミズク", yomi: "じごくみみずく", alias: "2-Much-2-Take" },
{ name: "ナンデナン", yomi: "なんでなん", alias: "Why Naant" },
{ name: "そーナンだー", yomi: "そーなんだー", alias: "Naandhi" },
{ name: "のっぺら坊", yomi: "のっぺらぼう", alias: "Faysoff" },
{ name: "ハナホ人", yomi: "はなほじん", alias: "Snottle" },
{ name: "ひじょうぐち", yomi: "ひじょうぐち", alias: "Legsit" },
{ name: "まるナゲット", yomi: "まるなげっと", alias: "Chukket" },
{ name: "ピントコーン", yomi: "ぴんとこーん", alias: "Cornfused" },
{ name: "カラヤブリ", yomi: "からやぶり", alias: "Unshelltered" },
{ name: "わらえ姉", yomi: "わらえねえ", alias: "Lafalotta" },
{ name: "青くちびる", yomi: "あおくちびる", alias: "Blips" },
{ name: "バクロ婆", yomi: "ばくろばあ", alias: "Tattletell" },
{ name: "ババァーン", yomi: "ばばぁーん", alias: "Tattlecast" },
{ name: "ドクロ婆", yomi: "どくろばあ", alias: "Skranny" },
{ name: "モテモ天", yomi: "もてもてん", alias: "Cupistol" },
{ name: "モテマクール", yomi: "もてまくーる", alias: "Casanuva" },
{ name: "モテヌス", yomi: "もてぬす", alias: "Casanono" },
{ name: "一旦ゴメン", yomi: "いったんごめん", alias: "So-Sorree" },
{ name: "あやまり倒し", yomi: "あやまりだおし", alias: "Bowminos" },
{ name: "こえんら", yomi: "こえんら", alias: "Smogling" },
{ name: "えんらえんら", yomi: "えんらえんら", alias: "Smogmella" },
{ name: "でんぱく小僧", yomi: "でんぱくこぞう", alias: "Signibble" },
{ name: "でんじん", yomi: "でんじん", alias: "Signiton" },
{ name: "おでんじん", yomi: "おでんじん", alias: "Master Oden" },
{ name: "はつでんしん", yomi: "はつでんしん", alias: "Statiking" },
{ name: "U.S.O.", yomi: "ゆーえすおー", alias: "Failian" },
{ name: "アペリカン", yomi: "あぺりかん", alias: "Apelican" },
{ name: "フウ2", yomi: "ふうつー", alias: "Fuu 2" },
{ name: "スットン卿", yomi: "すっとんきょう", alias: "Shrillington" },
{ name: "家ーイ", yomi: "いえーい", alias: "House Partay" },
{ name: "レインボーン", yomi: "れいんぼーん", alias: "Skulleidoscope" },
{ name: "ペラペライオン", yomi: "ぺらぺらいおん", alias: "Lionguist" },
{ name: "まぼ老師", yomi: "まぼろうし", alias: "Illoo" },
{ name: "かげ老師", yomi: "かげろうし", alias: "Elloo" },
{ name: "ほう老師", yomi: "ほうろうし", alias: "Alloo" },
{ name: "さとりちゃん", yomi: "さとりちゃん", alias: "Espy" },
{ name: "よつめ", yomi: "よつめ", alias: "Infour" },
{ name: "うんがい鏡", yomi: "うんがいきょう", alias: "Mirapo" },
{ name: "うんがい三面鏡", yomi: "うんがいさんめんきょう", alias: "Miradox" },
{ name: "ヤミ鏡", yomi: "やみかがみ", alias: "Mircle" },
{ name: "セバスチャン", yomi: "せばすちゃん", alias: "Verygoodsir" },
{ name: "せいでん鬼", yomi: "せいでんき", alias: "Statikid" },
{ name: "なぞトキ", yomi: "なぞとき", alias: "Prof. Plumage" },
{ name: "紙かくし", yomi: "かみかくし", alias: "Throne Wiper" },
{ name: "ヒマ神", yomi: "ひまじん", alias: "Imagenius" },
{ name: "ミス・テリー", yomi: "みすてりー", alias: "Miss Teri" },
{ name: "ニャン魔女", yomi: "にゃんまじょ", alias: "Maginyan" },
{ name: "オトナカイ", yomi: "おとなかい", alias: "Squandeer" },
{ name: "天狗", yomi: "てんぐ", alias: "Tengu" },
{ name: "ほむら天狗", yomi: "ほむらてんぐ", alias: "Flengu" },
{ name: "キュウビ", yomi: "きゅうび", alias: "Kyubi" },
{ name: "犬神", yomi: "いぬがみ", alias: "Frostail" },
{ name: "ぬえ", yomi: "ぬえ", alias: "Chymera" },
{ name: "風魔猿", yomi: "ふうまざる", alias: "Kingmera" },
{ name: "鬼ガマ", yomi: "おにがま", alias: "Toadal Demon" },
{ name: "酒呑童子", yomi: "しゅてんどうじ", alias: "Thurston" },
{ name: "バニー・ミント", yomi: "ばにーみんと", alias: "Spect-hare" },
{ name: "スノーラビィ", yomi: "すのーらびぃ", alias: "Sn. Spect-hare" },
{ name: "マイッカー", yomi: "まいっかー", alias: "Oh Wheel" },
{ name: "だるだるま", yomi: "だるだるま", alias: "Dulluma" },
{ name: "だるまっちょ", yomi: "だるまっちょ", alias: "Darumacho" },
{ name: "ゴリだるま", yomi: "ごりだるま", alias: "Goruma" },
{ name: "うらや飯", yomi: "うらやめし", alias: "Wotchagot" },
{ name: "プライ丼", yomi: "ぷらいどん", alias: "Pride Shrimp" },
{ name: "迷い車", yomi: "まよいぐるま", alias: "No-Go Kart" },
{ name: "だっせんしゃ", yomi: "だっせんしゃ", alias: "Mistank" },
{ name: "ドキ土器", yomi: "どきどき", alias: "Terrorpotta" },
{ name: "怒気ドキ土器", yomi: "どきどきどき", alias: "Blownhistoppa" },
{ name: "ムリカベ", yomi: "むりかべ", alias: "Noway" },
{ name: "むりだ城", yomi: "むりだじょう", alias: "Impass" },
{ name: "シロカベ", yomi: "しろかべ", alias: "Walldin" },
{ name: "グレるりん", yomi: "ぐれるりん", alias: "Roughraff" },
{ name: "ゴクドー", yomi: "ごくどー", alias: "Badude" },
{ name: "アニ鬼", yomi: "あにき", alias: "Bruff" },
{ name: "ブルックりん", yomi: "ぶるっくりん", alias: "Roughgraff" },
{ name: "あまん汁", yomi: "あまんじる", alias: "Chilled Cowcao" },
{ name: "ギュウ汁", yomi: "ぎゅうじる", alias: "Stircrazy Stu" },
{ name: "ポン骨", yomi: "ぽんこつ", alias: "Nummskull" },
{ name: "リボーン", yomi: "りぼーん", alias: "Skillskull" },
{ name: "ヨロイさん", yomi: "よろいさん", alias: "Armsman" },
{ name: "モノマネキン", yomi: "ものまねきん", alias: "Mimikin" },
{ name: "オーバーガー", yomi: "おーばーがー", alias: "Oh Bah Gah!" },
{ name: "魔ウンテン", yomi: "まうんてん", alias: "Sp mountain" },
{ name: "トオセンボン", yomi: "とおせんぼん", alias: "Blowkade" },
{ name: "くろがねセンボン", yomi: "くろがねせんぼん", alias: "Ledballoon" },
{ name: "すもうどん", yomi: "すもうどん", alias: "Sumodon" },
{ name: "横綱うどん", yomi: "よこづなうどん", alias: "Yokozudon" },
{ name: "あっそう山", yomi: "あっそうざん", alias: "Whateverest" },
{ name: "あそっ火山", yomi: "あそっかざん", alias: "Whatuption" },
{ name: "モレゾウ", yomi: "もれぞう", alias: "Fidgephant" },
{ name: "プルファント", yomi: "ぷるふぁんと", alias: "Touphant" },
{ name: "ガマンモス", yomi: "がまんもす", alias: "Enduriphant" },
{ name: "雷蔵", yomi: "らいぞう", alias: "Zappary" },
{ name: "ヒライ神", yomi: "ひらいしん", alias: "Frazzel" },
{ name: "あっけら艦", yomi: "あっけらかん", alias: "Ship. Sailor" },
{ name: "シレイ艦", yomi: "しれいかん", alias: "Adm. Admiral" },
{ name: "あせっか鬼", yomi: "あせっかき", alias: "Swelton" },
{ name: "シングコング", yomi: "しんぐこんぐ", alias: "Sing Kong" },
{ name: "カメッパ", yomi: "かめっぱ", alias: "Slippy" },
{ name: "おくらいり", yomi: "おくらいり", alias: "Repossessor" },
{ name: "カクさん", yomi: "かくさん", alias: "Mr. Blockhead" },
{ name: "ふじのやま", yomi: "ふじのやま", alias: "Mad Mountain" },
{ name: "さくらのじま", yomi: "さくらのじま", alias: "Lava Lord" },
{ name: "ドウカク", yomi: "どうかく", alias: "Castelius III" },
{ name: "ギンカク", yomi: "ぎんかく", alias: "Castelius II" },
{ name: "キンカク", yomi: "きんかく", alias: "Castelius I" },
{ name: "プラチナカク", yomi: "ぷらちなかく", alias: "Castelius Max" },
{ name: "イヌニャン", yomi: "いぬにゃん", alias: "Puppynyan" },
{ name: "武者かぶと", yomi: "むしゃかぶと", alias: "Rhinoggin" },
{ name: "かぶと無双", yomi: "かぶとむそう", alias: "Rhinormous" },
{ name: "オオツノノ神", yomi: "おおつののかみ", alias: "Hornaplenty" },
{ name: "キンタロニャン", yomi: "きんたろにゃん", alias: "Kintaronyan" },
{ name: "ステーキング", yomi: "すてーきんぐ", alias: "Steaking" },
{ name: "ロボニャン", yomi: "ろぼにゃん", alias: "Robonyan" },
{ name: "ロボニャンF型", yomi: "ろぼにゃんえふがた", alias: "Robonyan F" },
{ name: "ロボニャンUSA", yomi: "ろぼにゃんゆーえすえー", alias: "Showbonyan" },
{ name: "ゴルニャン", yomi: "ごるにゃん", alias: "Goldenyan" },
{ name: "だいだらぼっち", yomi: "だいだらぼっち", alias: "Dromp" },
{ name: "うみぼうず", yomi: "うみぼうず", alias: "Swosh" },
{ name: "大ガマ", yomi: "おおがま", alias: "Toadal Dude" },
{ name: "大やもり", yomi: "おおやもり", alias: "Uber Geeko" },
{ name: "赤鬼", yomi: "あかおに", alias: "Gragaros" },
{ name: "青鬼", yomi: "あおおに", alias: "Ogralus" },
{ name: "黒鬼", yomi: "くろおに", alias: "Orcanos" },
{ name: "カブキロイド", yomi: "かぶきろいど", alias: "Kabuking" },
{ name: "ザ・シャーク", yomi: "ざしゃーく", alias: "Jawsome Kid" },
{ name: "エル・シャクレロ", yomi: "えるしゃくれろ", alias: "El Sharkador" },
{ name: "スカイシャリマン", yomi: "すかいしゃりまん", alias: "Silver Lining" },
{ name: "びきゃく", yomi: "びきゃく", alias: "Leggly" },
{ name: "ピヨピヨコ", yomi: "ぴよぴよこ", alias: "Twirly Pie" },
{ name: "ほっとケーキ", yomi: "ほっとけーき", alias: "Petty-Cake" },
{ name: "いきあたりバッタ", yomi: "いきあたりばった", alias: "Hoppy." },
{ name: "しゃれこ婦人", yomi: "しゃれこふじん", alias: "Dazzabel" },
{ name: "カラカラさん", yomi: "からからさん", alias: "Rattelle" },
{ name: "ほね美人", yomi: "ほねびじん", alias: "Skelebella" },
{ name: "セミまる", yomi: "せみまる", alias: "Cadin" },
{ name: "カゲまる", yomi: "かげまる", alias: "Cadable" },
{ name: "ヒグラシまる", yomi: "ひぐらしまる", alias: "Singcada" },
{ name: "こてんパン", yomi: "こてんぱん", alias: "Buttered Blue" },
{ name: "大化ケット", yomi: "おおばけっと", alias: "Pch. Baguette" },
{ name: "さむガリ", yomi: "さむがり", alias: "Pupsicle" },
{ name: "ガリ王子", yomi: "がりおうじ", alias: "Chilhuahua" },
{ name: "あつガルル", yomi: "あつがるる", alias: "Swelterrier" },
{ name: "アンビリバ坊", yomi: "あんびりばぼう", alias: "Unbelievaboy!" },
{ name: "バッド坊や", yomi: "ばっどぼうや", alias: "Unbearaboy!" },
{ name: "激辛ボーイ", yomi: "げきからぼーい", alias: "Inflammaboy!" },
{ name: "つらがわり", yomi: "つらがわり", alias: "Jumbelina" },
{ name: "一つ目小僧", yomi: "ひとつめこぞう", alias: "Boyclops" },
{ name: "コンたん", yomi: "こんたん", alias: "Krystal Fox" },
{ name: "わかランナー", yomi: "わからんなー", alias: "Runsure" },
{ name: "寝コロンブス", yomi: "ねころんぶす", alias: "Kittylumbus" },
{ name: "デモネード", yomi: "でもねーど", alias: "Zest-a-Minute" },
{ name: "バク", yomi: "ばく", alias: "Baku" },
{ name: "ハク", yomi: "はく", alias: "Whapir" },
{ name: "おバク様", yomi: "おばくさま", alias: "Bakulia" },
{ name: "江戸っ子パンダ", yomi: "えどっこぱんだ", alias: "Panja Pupil" },
{ name: "大江戸忍者パンダ", yomi: "おおえどにんじゃぱんだ", alias: "Panja Pro" },
{ name: "カンペちゃん", yomi: "かんぺちゃん", alias: "Cue-Tee" },
{ name: "無茶ぶりっ子", yomi: "むちゃぶりっこ", alias: "Demandi" },
{ name: "ノガッパ", yomi: "のがっぱ", alias: "Walkappa" },
{ name: "たびガッパ", yomi: "たびがっぱ", alias: "Appak" },
{ name: "なみガッパ", yomi: "なみがっぱ", alias: "Supyo" },
{ name: "ジバニャン", yomi: "じばにゃん", alias: "Jibanyan" },
{ name: "Bジバニャン", yomi: "びーじばにゃん", alias: "Jibanyan B" },
{ name: "ジバニャンS", yomi: "じばにゃんえす", alias: "Jibanyan S" },
{ name: "ジバニャン劉備", yomi: "じばにゃんりゅうび", alias: "Jiban. Liu Bei" },
{ name: "アカマル", yomi: "あかまる", alias: "Rudy" },
{ name: "トゲニャン", yomi: "とげにゃん", alias: "Thornyan" },
{ name: "ワルニャン", yomi: "わるにゃん", alias: "Baddinyan" },
{ name: "ブチニャン", yomi: "ぶちにゃん", alias: "Buchinyan" },
{ name: "コマさん", yomi: "こまさん", alias: "Komasan" },
{ name: "ししコマ", yomi: "ししこま", alias: "Komane" },
{ name: "Bコマさん", yomi: "びーこまさん", alias: "Komasan B" },
{ name: "コマさんS", yomi: "こまさんえす", alias: "Komasan B" },
{ name: "コマさん孫策", yomi: "こまさんそんさく", alias: "Koma. Sun Ce" },
{ name: "ジバコマ", yomi: "じばこま", alias: "Jibakoma" },
{ name: "コマじろう", yomi: "こまじろう", alias: "Komajiro" },
{ name: "とらじろう", yomi: "とらじろう", alias: "Komiger" },
{ name: "コマじろうS", yomi: "こまじろうえす", alias: "Komajiro S" },
{ name: "雨女", yomi: "あめおんな", alias: "Drizzelda" },
{ name: "ばくそく", yomi: "ばくそく", alias: "Nekidspeed" },
{ name: "ナンスカンク", yomi: "なんすかんく", alias: "Stinkeye" },
{ name: "おきラクーン", yomi: "おきらくーん", alias: "Slackoon" },
{ name: "おとなブル", yomi: "おとなぶる", alias: "Puppiccino" },
{ name: "たまのこし", yomi: "たまのこし", alias: "Ballin" },
{ name: "キュン太郎", yomi: "きゅんたろう", alias: "Shmoopie" },
{ name: "ズキュキュン太", yomi: "ずきゅきゅんた", alias: "Pinkipoo" },
{ name: "裏キュン太", yomi: "うらきゅんた", alias: "Pookivil" },
{ name: "ケマモン", yomi: "けまもん", alias: "Harry Barry" },
{ name: "ワンダーニャン", yomi: "わんだーにゃん", alias: "Wondernyan" },
{ name: "ジェットニャン", yomi: "じぇっとにゃん", alias: "Jetnyan" },
{ name: "サルニャン", yomi: "さるにゃん", alias: "Chimpanyan" },
{ name: "トムニャン", yomi: "とむにゃん", alias: "Tomnyan" },
{ name: "KKブラザーズ", yomi: "けーけーぶらざーず", alias: "Koma Knomads" },
{ name: "ゆきおんな", yomi: "ゆきおんな", alias: "Frostina" },
{ name: "ふぶき姫", yomi: "ふぶきひめ", alias: "Blizzaria" },
{ name: "百鬼姫", yomi: "ひゃっきひめ", alias: "Damona" },
{ name: "メロンニャン", yomi: "めろんにゃん", alias: "Melonyan" },
{ name: "ミカンニャン", yomi: "みかんにゃん", alias: "Oranyan" },
{ name: "キウイニャン", yomi: "きういにゃん", alias: "Kiwinyan" },
{ name: "ブドウニャン", yomi: "ぶどうにゃん", alias: "Grapenyan" },
{ name: "イチゴニャン", yomi: "いちごにゃん", alias: "Strawbnyan" },
{ name: "スイカニャン", yomi: "すいかにゃん", alias: "Watermelnyan" },
{ name: "サファイニャン", yomi: "さふぁいにゃん", alias: "Saphhinyan" },
{ name: "エメラルニャン", yomi: "えめらるにゃん", alias: "Emenyan" },
{ name: "ルビーニャン", yomi: "るびーにゃん", alias: "Rubinyan" },
{ name: "トパニャン", yomi: "とぱにゃん", alias: "Topanyan" },
{ name: "ダイヤニャン", yomi: "だいやにゃん", alias: "Dianyan" },
{ name: "ロボガッパ", yomi: "ろぼがっぱ", alias: "Robokapp" },
{ name: "ロボコマ", yomi: "ろぼこま", alias: "Robokoma" },
{ name: "セーラーニャン", yomi: "せーらーにゃん", alias: "Sailornyan" },
{ name: "レッドJ", yomi: "れっどじぇー", alias: "Rubeus J" },
{ name: "マイティードッグ", yomi: "まいてぃーどっぐ", alias: "Hardy Hound" },
{ name: "かまいたち", yomi: "かまいたち", alias: "Whirlweasel" },
{ name: "チョコボニャン", yomi: "ちょこぼにゃん", alias: "Chochobonyan" },
{ name: "モーグリニャン", yomi: "もーぐりにゃん", alias: "Mooglenyan" },
{ name: "ぷにニャン", yomi: "ぷににゃん", alias: "Wobblenyan" },
{ name: "ぷにコマ", yomi: "ぷにこま", alias: "Wibblekoma" },
{ name: "スシジバ", yomi: "すしじば", alias: "Sushinyan" },
{ name: "天コマ", yomi: "てんこま", alias: "Tempurasan" },
{ name: "河童", yomi: "かっぱ", alias: "Faux Kappa" },
{ name: "水虎", yomi: "すいこ", alias: "Tigappa" },
{ name: "マスターニャーダ", yomi: "ますたーにゃーだ", alias: "Master Nyada" },
{ name: "烏天狗", yomi: "からすてんぐ", alias: "Tenguriginal" },
{ name: "カルラ", yomi: "かるら", alias: "Tengulightened" },
{ name: "から傘お化け", yomi: "からかさおばけ" },
{ name: "モ作", yomi: "もさく" },
{ name: "ハーモリー", yomi: "はーもりー" },
{ name: "うらやましろう", yomi: "うらやましろう" },
{ name: "つまみぐいのすけ", yomi: "つまみぐいのすけ" },
{ name: "ワカメくん", yomi: "わかめくん" },
{ name: "ワカメ☆スター", yomi: "わかめすたー" },
{ name: "コンブさん", yomi: "こんぶさん" },
{ name: "メカブちゃん", yomi: "めかぶちゃん" },
{ name: "モズク先生", yomi: "もずくせんせい" },
{ name: "ひも爺", yomi: "ひもじい" },
{ name: "くいい爺", yomi: "くいいじい" },
{ name: "こめ爺", yomi: "こめじい" },
{ name: "ハングリーG", yomi: "はんぐりーじー" },
{ name: "キズナメコ", yomi: "きずなめこ" },
{ name: "キズナース", yomi: "きずなーす" },
{ name: "砂夫", yomi: "すなお" },
{ name: "大山砂夫", yomi: "おおやますなお" },
{ name: "風呂ずきん", yomi: "ふろずきん" },
{ name: "ふろーラル", yomi: "ふろーらる" },
{ name: "アフロ13", yomi: "あふろさーてぃーん" },
{ name: "てんてこ米", yomi: "てんてこまい" },
{ name: "あしたガール", yomi: "あしたがーる" },
{ name: "どっちつかず", yomi: "どっちつかず" },
{ name: "ポチッ", yomi: "ぽちっ" },
{ name: "ウキウキビ", yomi: "うきうきび" },
{ name: "トキメキビ", yomi: "ときめきび" },
{ name: "びんボーイ", yomi: "びんぼーい" },
{ name: "お金ナイダー", yomi: "おかねないだー" },
{ name: "らくてん童", yomi: "らくてんどう" },
{ name: "ざしきわらし", yomi: "ざしきわらし" },
{ name: "ざしきわら神", yomi: "ざしきわらしん" },
{ name: "ぜっこう蝶（ゼッコウ蝶）", yomi: "ぜっこうちょう" },
{ name: "サイコウ蝶", yomi: "さいこうちょう" },
{ name: "アゲアゲハ", yomi: "あげあげは" },
{ name: "くだん", yomi: "くだん" },
{ name: "大くだん", yomi: "だいくだん" },
{ name: "どんちゃん", yomi: "どんちゃん" },
{ name: "晴れ男", yomi: "はれおとこ" },
{ name: "サンタク老師", yomi: "さんたくろうし" },
{ name: "ふくろじじい", yomi: "ふくろじじい" },
{ name: "カンガエルー", yomi: "かんがえるー" },
{ name: "はなしカミ", yomi: "はなしかみ" },
{ name: "サンデーパパ", yomi: "さんでーぱぱ" },
{ name: "ガッテンマイヤー", yomi: "がってんまいやー" },
{ name: "エコロ爺", yomi: "えころじい" },
{ name: "イーセンイッテル", yomi: "いーせんいってる" },
{ name: "カントリーバァバ", yomi: "かんとりーばぁば" },
{ name: "ホノボーノ", yomi: "ほのぼーの" },
{ name: "ヒョウヘンヌ", yomi: "ひょうへんぬ" },
{ name: "ヒョウヘンナ", yomi: "ひょうへんな" },
{ name: "キジニャン", yomi: "きじにゃん" },
{ name: "ハッピィさん", yomi: "はっぴぃさん" },
{ name: "歯磨貴婦人", yomi: "はみがきふじん" },
{ name: "ロボG", yomi: "ろぼじー" },
{ name: "さいの目入道", yomi: "さいのめにゅうどう" },
{ name: "ゾロ目大明神", yomi: "ぞろめだいみょうじん" },
{ name: "から傘魔人", yomi: "からかさまじん" },
{ name: "ウラシマニャン", yomi: "うらしまにゃん" },
{ name: "いたれりつくせり", yomi: "いたれりつくせり" },
{ name: "雷オトン", yomi: "らいおとん" },
{ name: "絶オジイ", yomi: "ぜつおじい" },
{ name: "聖オカン", yomi: "せいおかん" },
{ name: "心オバア", yomi: "しんおばあ" },
{ name: "麒麟", yomi: "きりん" },
{ name: "イッカク", yomi: "いっかく" },
{ name: "スピーディーW", yomi: "すぴーでぃーだぶる" },
{ name: "カンフーマッハ", yomi: "かんふーまっは" },
{ name: "やるせナス", yomi: "やるせなす" },
{ name: "チクリ魔", yomi: "ちくりま" },
{ name: "ちらかし家来", yomi: "ちらかしけらい" },
{ name: "みちび鬼", yomi: "みちびき" },
{ name: "えこひい鬼", yomi: "えこひいき" },
{ name: "かたのり小僧", yomi: "かたのりこぞう" },
{ name: "かたのり親方", yomi: "かたのりおやかた" },
{ name: "ぎっくり男", yomi: "ぎっくりおとこ" },
{ name: "草くい男", yomi: "くさくいおとこ" },
{ name: "肉くい男", yomi: "にくくいおとこ" },
{ name: "TETSUYA", yomi: "てつや" },
{ name: "KANTETSU", yomi: "かんてつ" },
{ name: "つぶや木", yomi: "つぶやき" },
{ name: "ツリート", yomi: "つりーと" },
{ name: "ネガティブーン", yomi: "ねがてぃぶーん" },
{ name: "ジャネガブーン", yomi: "じゃねがぶーん" },
{ name: "かゆかゆ", yomi: "かゆかゆ" },
{ name: "ジミー", yomi: "じみー" },
{ name: "カゲロー", yomi: "かげろー" },
{ name: "カイム", yomi: "かいむ" },
{ name: "カリカリベーコン", yomi: "かりかりべーこん" },
{ name: "ぎしんあん鬼", yomi: "ぎしんあんき" },
{ name: "ガ鬼", yomi: "がき" },
{ name: "あまのじゃく", yomi: "あまのじゃく" },
{ name: "ジンギスギスカン", yomi: "じんぎすぎすかん" },
{ name: "チンギスギスハン", yomi: "ちんぎすぎすはん" },
{ name: "ヒキコウモリ", yomi: "ひきこうもり" },
{ name: "トジコウモリ", yomi: "とじこうもり" },
{ name: "ヤドコウモリ", yomi: "やどこうもり" },
{ name: "かりパックン", yomi: "かりぱっくん" },
{ name: "泥ボックン", yomi: "どろぼっくん" },
{ name: "ギーくん", yomi: "ぎーくん" },
{ name: "ハッキング", yomi: "はっきんぐ" },
{ name: "ひとまか仙人", yomi: "ひとまかせんにん" },
{ name: "りもこんかくし", yomi: "りもこんかくし" },
{ name: "ジコチュウ", yomi: "じこちゅう" },
{ name: "じこけん王", yomi: "じこけんおう" },
{ name: "インチキン", yomi: "いんちきん" },
{ name: "あんのジョー", yomi: "あんのじょー" },
{ name: "アイタタタイムズ", yomi: "あいたたたいむず" },
{ name: "ゴジダツ爺", yomi: "ごじだつじい" },
{ name: "ネクラマテング", yomi: "ねくらまてんぐ" },
{ name: "ヨミテング", yomi: "よみてんぐ" },
{ name: "まてんし", yomi: "まてんし" },
{ name: "リー夫人", yomi: "りーふじん" },
{ name: "ガブニャン", yomi: "がぶにゃん" },
{ name: "カッパー", yomi: "かっぱー" },
{ name: "ダリス", yomi: "だりす" },
{ name: "USAピョン", yomi: "うさぴょん" },
{ name: "B-USAピョン", yomi: "びーうさぴょん" },
{ name: "USAピョン仲達", yomi: "うさぴょんちゅうたつ" },
{ name: "ミツマタノヅチ", yomi: "みつまたのづち" },
{ name: "魔ガサス", yomi: "まがさす" },
{ name: "ウ魔", yomi: "うま" },
{ name: "ガシャどくろ", yomi: "がしゃどくろ" },
{ name: "デビビル", yomi: "でびびる" },
{ name: "デビビラン", yomi: "でびびらん" },
{ name: "虫歯伯爵", yomi: "むしばはくしゃく" },
{ name: "百々目鬼", yomi: "とどめき" },
{ name: "きらめ鬼", yomi: "きらめき" },
{ name: "ドケチング", yomi: "どけちんぐ" },
{ name: "ヤミまろ", yomi: "やみまろ" },
{ name: "どんどろ", yomi: "どんどろ" },
{ name: "ヤミキュウビ", yomi: "やみきゅうび" },
{ name: "ゼロ博士", yomi: "ぜろはかせ" },
{ name: "Dr.カゲムラ", yomi: "どくたーかげむら" },
{ name: "魔天王", yomi: "まてんおう" },
{ name: "かえりタイ", yomi: "かえりたい" },
{ name: "やぶレター", yomi: "やぶれたー" },
{ name: "てのひらがえし", yomi: "てのひらがえし" },
{ name: "あしでまとい", yomi: "あしでまとい" },
{ name: "イガイガグリ", yomi: "いがいがぐり" },
{ name: "チクチクウニ", yomi: "ちくちくうに" },
{ name: "じめりんぼう", yomi: "じめりんぼう" },
{ name: "雨ふらし", yomi: "あめふらし" },
{ name: "こおりんぼう", yomi: "こおりんぼう" },
{ name: "化けあられ", yomi: "ばけあられ" },
{ name: "たらりん", yomi: "たらりん" },
{ name: "ヨコドリ", yomi: "よこどり" },
{ name: "ぶんぶん鳥", yomi: "ぶんぶんどり" },
{ name: "はらおドリ", yomi: "はらおどり" },
{ name: "おともらし", yomi: "おともらし" },
{ name: "爆音ならし", yomi: "爆音ならし" },
{ name: "トホホギス", yomi: "とほほぎす" },
{ name: "ブカッコウ", yomi: "ぶかっこう" },
{ name: "死神鳥", yomi: "しにがみどり" },
{ name: "じんめん犬", yomi: "じんめんけん" },
{ name: "かおベロス", yomi: "かおべろす" },
{ name: "三途の犬", yomi: "さんずのいぬ" },
{ name: "けうけげん", yomi: "けうけげん" },
{ name: "ふさふさん", yomi: "ふさふさん" },
{ name: "たいこモチ", yomi: "たいこもち" },
{ name: "ごまスリー", yomi: "ごますりー" },
{ name: "認MEN", yomi: "みとめん" },
{ name: "黄ばんドール", yomi: "きばんどーる" },
{ name: "ふあんかん", yomi: "ふあんかん" },
{ name: "たらいまわし", yomi: "たらいまわし" },
{ name: "口だけおんな", yomi: "くちだけおんな" },
{ name: "おつぼね様", yomi: "おつぼねさま" },
{ name: "ドンヨリーヌ", yomi: "どんよりーぬ" },
{ name: "シメッポイーナ", yomi: "しめっぽいーな" },
{ name: "砂ン丘入道", yomi: "さんきゅうにゅうどう" },
{ name: "ノー砂ン丘入道", yomi: "のーさんきゅうにゅうどう" },
{ name: "じがじぃさん", yomi: "じがじぃさん" },
{ name: "のらりくらり", yomi: "のらりくらり" },
{ name: "おすべり様", yomi: "おすべりさま" },
{ name: "おしっしょう", yomi: "おしっしょう" },
{ name: "おひとり様", yomi: "おひとりさま" },
{ name: "テンパるんバ", yomi: "てんぱるんば" },
{ name: "こしパンダ", yomi: "こしぱんだ" },
{ name: "おならず者", yomi: "おならずもの" },
{ name: "へこ鬼神", yomi: "へこきじん" },
{ name: "花子さん", yomi: "はなこさん" },
{ name: "呪野花子", yomi: "のろいのはなこ" },
{ name: "ロボメン犬", yomi: "ろぼめんけん" },
{ name: "けちらし", yomi: "けちらし" },
{ name: "アンラッキィさん", yomi: "あんらっきぃさん" },
{ name: "ヨッチャ〜", yomi: "よっちゃー" },
{ name: "しわくちゃん", yomi: "しわくちゃん" },
{ name: "老いらん", yomi: "おいらん" },
{ name: "ふじみ御前", yomi: "ふじみごぜん" },
{ name: "のぼせトンマン", yomi: "のぼせとんまん" },
{ name: "ダークニャン", yomi: "だーくにゃん" },
{ name: "決めて魔王", yomi: "きめてまおう" },
{ name: "おとろし", yomi: "おとろし" },
{ name: "フゥミン", yomi: "ふぅみん" },
{ name: "おねむの精", yomi: "おねむのせい" },
{ name: "土蜘蛛", yomi: "つちぐも" },
{ name: "女郎蜘蛛", yomi: "じょろうぐも" },
{ name: "オリジン", yomi: "おりじん" },
{ name: "ファントム", yomi: "ふぁんとむ" },
{ name: "サキちゃん", yomi: "さきちゃん" },
{ name: "ねちがえる", yomi: "ねちがえる" },
{ name: "バンジーきゅうす", yomi: "ばんじーきゅうす" },
{ name: "マイマイペース", yomi: "まいまいぺーす" },
{ name: "ダソックス", yomi: "だそっくす" },
{ name: "アーダコンダ", yomi: "あーだこんだ" },
{ name: "ツチノコ", yomi: "つちのこ" },
{ name: "フクリュウ", yomi: "ふくりゅう" },
{ name: "ツチノコパンダ", yomi: "つちのこぱんだ" },
{ name: "ツチノコ星人", yomi: "つちのこせいじん" },
{ name: "からみぞん", yomi: "からみぞん" },
{ name: "こんがらギャル", yomi: "こんがらぎゃる" },
{ name: "オッタマゲーター", yomi: "おったまげーたー" },
{ name: "ナンモナイト", yomi: "なんもないと" },
{ name: "カイーギョ", yomi: "かいーぎょ" },
{ name: "笑ウツボ", yomi: "わらうつぼ" },
{ name: "歌ウナギ", yomi: "うたうなぎ" },
{ name: "大蛇のツボ", yomi: "だいじゃのつぼ" },
{ name: "たこやっ鬼", yomi: "たこやっき" },
{ name: "たこや鬼神", yomi: "たこやきじん" },
{ name: "キライギョ", yomi: "きらいぎょ" },
{ name: "ゾウオ", yomi: "ぞうお" },
{ name: "ギャクジョウオ", yomi: "ぎゃくじょうお" },
{ name: "おもいだスッポン", yomi: "おもいだすっぽん" },
{ name: "おもいだ神", yomi: "おもいだしん" },
{ name: "ムカムカデ", yomi: "むかむかで" },
{ name: "激ドラゴン", yomi: "げきどらごん" },
{ name: "りゅーくん", yomi: "りゅーくん" },
{ name: "龍神", yomi: "りゅうじん" },
{ name: "青龍", yomi: "せいりゅう" },
{ name: "にんぎょ", yomi: "にんぎょ" },
{ name: "八百比丘尼", yomi: "やおびくに" },
{ name: "イザナミ", yomi: "いざなみ" },
{ name: "ダイナシー", yomi: "だいなしー" },
{ name: "D-レックス", yomi: "でぃーれっくす" },
{ name: "ドジラ", yomi: "どじら" },
{ name: "ろくろ首", yomi: "ろくろくび" },
{ name: "ウィスパー", yomi: "うぃすぱー" },
{ name: "ウィスベェ", yomi: "うぃすべぇ" },
{ name: "キリスギリス", yomi: "きりすぎりす" },
{ name: "ひっぱりダコ", yomi: "ひっぱりだこ" },
{ name: "たこうらみ", yomi: "たこうらみ" },
{ name: "ボー坊", yomi: "ぼーぼう" },
{ name: "しどろもどろ", yomi: "しどろもどろ" },
{ name: "ミチクサメ", yomi: "みちくさめ" },
{ name: "トーシロザメ", yomi: "とーしろざめ" },
{ name: "ムダヅカイ", yomi: "むだづかい" },
{ name: "はらわシェル", yomi: "はらわしぇる" },
{ name: "ナガバナ", yomi: "ながばな" },
{ name: "ナガバナナ", yomi: "ながばなな" },
{ name: "チョコバナーナ", yomi: "ちょこばなーな" },
{ name: "ホリュウ", yomi: "ほりゅう" },
{ name: "ロボノコ", yomi: "ろぼのこ" },
{ name: "ロボりゅーくん", yomi: "ろぼりゅーくん" },
{ name: "油すまし", yomi: "あぶらすまし" },
{ name: "しきるん蛇", yomi: "しきるんじゃ" },
{ name: "すねスネーク", yomi: "すねすねーく" },
{ name: "まむし行司", yomi: "まむしぎょうじ" },
{ name: "つられたろう丸", yomi: "つられたろうまる" },
{ name: "おれリュウ", yomi: "おれりゅう" },
{ name: "オロチ", yomi: "おろち" },
{ name: "影オロチ", yomi: "かげおろち" },
{ name: "センポクカンポク", yomi: "せんぽくかんぽく" },
{ name: "マッサラニャン", yomi: "まっさらにゃん" },
{ name: "アンドロイド山田", yomi: "あんどろいどやまだ" },
{ name: "厄怪", yomi: "やっかい" },
{ name: "不怪", yomi: "ふかい" },
{ name: "豪怪", yomi: "ごうかい" },
{ name: "難怪", yomi: "なんかい" },
{ name: "破怪", yomi: "はかい" },
{ name: "あかなめ・怪", yomi: "あかなめかい" },
{ name: "泥田坊・怪", yomi: "どろたぼうかい" },
{ name: "えんらえんら・怪", yomi: "えんらえんらかい" },
{ name: "河童・怪", yomi: "かっぱかい" },
{ name: "から傘お化け・怪", yomi: "からかさおばけかい" },
{ name: "ざしきわらし・怪", yomi: "ざしきわらしかい" },
{ name: "くだん・怪", yomi: "くだんかい" },
{ name: "けうけげん・怪", yomi: "けうけげんかい" },
{ name: "にんぎょ・怪", yomi: "にんぎょかい" },
{ name: "ろくろ首・怪", yomi: "ろくろくびかい" },
{ name: "ジバニャンK", yomi: "じばにゃんきんぐ" },
{ name: "USAピョンQ", yomi: "うさぴょんくいーん" },
{ name: "コマさんJ", yomi: "こまさんじゃっく" },
{ name: "コマじゅうろう", yomi: "こまじゅうろう" },
{ name: "フユニャンA", yomi: "ふゆにゃんえーす" },
{ name: "ウィスババ", yomi: "うぃすばば" },
{ name: "弁財天", yomi: "べんざいてん" },
{ name: "布袋尊", yomi: "ほていそん" },
{ name: "大黒天", yomi: "だいこくてん" },
{ name: "恵比寿", yomi: "えびす" },
{ name: "毘沙門天", yomi: "びしゃもんてん" },
{ name: "コロンブス", yomi: "ころんぶす" },
{ name: "エジソン", yomi: "えじそん" },
{ name: "ダーウィン", yomi: "だーうぃん" },
{ name: "ラストブシニャン", yomi: "らすとぶしにゃん" },
{ name: "キラコマ", yomi: "きらこま" },
{ name: "プラチナ鬼", yomi: "ぷらちなおに" },
{ name: "ブルジョワG", yomi: "ぶるじょわじー" },
{ name: "ブシニャン", yomi: "ぶしにゃん" },
{ name: "しゅらコマ", yomi: "しゅらこま" },
{ name: "山吹鬼", yomi: "やまぶきおに" },
{ name: "ネタバレリーナ", yomi: "ねたばれりーな" },
{ name: "花さか爺", yomi: "はなさかじい" },
{ name: "うんちく魔", yomi: "うんちくま" },
{ name: "イケメン犬", yomi: "いけめんけん" },
{ name: "やまタン", yomi: "やまたん" },
{ name: "ばたんQ", yomi: "ばたんきゅー" },
{ name: "乙姫", yomi: "おとひめ" },
{ name: "あしゅら", yomi: "あしゅら" },
{ name: "ニャーミネーター", yomi: "にゃーみねーたー" },
{ name: "ヒーローニャン", yomi: "ひーろーにゃん" },
{ name: "フユニャンS", yomi: "ふゆにゃんえす" },
{ name: "フユニャン曹操", yomi: "ふゆにゃんそうそう" },
{ name: "ひとりよがり", yomi: "ひとりよがり" },
{ name: "ウォール・ガイ", yomi: "うぉーるがい" },
{ name: "ガランドゥ", yomi: "がらんどぅ" },
{ name: "バケルトン", yomi: "ばけるとん" },
{ name: "メカオロチ", yomi: "めかおろち" },
{ name: "黒鬼呂布", yomi: "くろおにりょふ" },
{ name: "メカキュウビ", yomi: "めかきゅうび" },
{ name: "Uロボニャン", yomi: "あるてぃめっとろぼにゃん" },
{ name: "デバミ", yomi: "でばみ" },
{ name: "しらんプリン", yomi: "しらんぷりん" },
{ name: "ミーフー", yomi: "みーふー" },
{ name: "コアラニャン", yomi: "こあらにゃん" },
{ name: "Tジバニャン", yomi: "とれじゃーじばにゃん" },
{ name: "Tコマさん", yomi: "とれじゃーこまさん" },
{ name: "卵の君", yomi: "たまごのきみ" },
{ name: "ワルノリン", yomi: "わるのりん" },
{ name: "サニーレタスさん", yomi: "さにーれたすさん" },
{ name: "テレテル坊主", yomi: "てれてるぼうず" },
{ name: "モルラ", yomi: "もるら" },
{ name: "ミカエリ", yomi: "みかえり" },
{ name: "一旦ソーリー", yomi: "いったんそーりー" },
{ name: "ヨドム", yomi: "よどむ" },
{ name: "まんまミーラ", yomi: "まんまみーら" },
{ name: "ダークコマー", yomi: "だーくこまー" },
{ name: "USA豆腐", yomi: "うさどうふ" },
{ name: "夜行", yomi: "やぎょう" },
{ name: "ゴージャス大使", yomi: "ごーじゃすたいし" },
{ name: "日ノ神", yomi: "ひのしん" },
{ name: "ぬらりひょん", yomi: "ぬらりひょん" },
{ name: "さきのばし", yomi: "さきのばし" },
{ name: "オタカラもどき", yomi: "おたからもどき" },
{ name: "ジャンクコシノ", yomi: "じゃんくこしの" },
{ name: "ウィスパー孔明", yomi: "うぃすぱーこうめい" },
{ name: "寿老人", yomi: "じゅろうじん" },
{ name: "福禄寿", yomi: "ふくろくじゅ" },
{ name: "マジンカーメン", yomi: "まじんかーめん" },
{ name: "ゴーキングデッド", yomi: "ごーきんぐでっど" },
{ name: "パンドラ", yomi: "ぱんどら" },
{ name: "リアクション大王", yomi: "りあくしょんだいおう" },
{ name: "ニャステト", yomi: "にゃすてと" },
{ name: "ズラビス", yomi: "ずらびす" },
{ name: "スピーチ姫", yomi: "すぴーちひめ" },
{ name: "トリベア", yomi: "とりべあ" },
{ name: "ジェントル面犬", yomi: "じぇんとるめんけん" },
{ name: "自慢ハッタン", yomi: "じまんはったん" },
{ name: "難陀竜王", yomi: "なんだりゅうおう" },
{ name: "エンマ大王", yomi: "えんまだいおう" },
{ name: "ぬらり神", yomi: "ぬらりしん" },
{ name: "覚醒日ノ神", yomi: "かくせいひのしん" },
{ name: "先代エンマ大王", yomi: "せんだいえんまだいおう" },
{ name: "覚醒エンマ", yomi: "かくせいえんま" },
{ name: "ノストラダマス", yomi: "のすとらだます" },
{ name: "シヴァラク", yomi: "しゔぁらく" },
{ name: "銅拍子", yomi: "どうびょうし" },
{ name: "吽形", yomi: "うんぎょう" },
{ name: "阿形", yomi: "あぎょう" },
{ name: "おんもらき", yomi: "おんもらき" },
{ name: "ちょうちんお化け", yomi: "ちょうちんおばけ" },
{ name: "牛頭", yomi: "ごず" },
{ name: "馬頭", yomi: "めず" },
{ name: "イソノナミ", yomi: "いそのなみ" },
{ name: "ヤマオカミ", yomi: "やまおかみ" },
{ name: "ツキノヤミ", yomi: "つきのやみ" },
{ name: "ふぶきちゃん", yomi: "ふぶきちゃん" },
{ name: "KJ", yomi: "けーじぇー" },
{ name: "太陽神エンマ", yomi: "たいようしんえんま" },
{ name: "時空神エンマ", yomi: "じくうしんえんま" },
{ name: "暗黒神エンマ", yomi: "あんこくしんえんま" },
{ name: "インディー・J", yomi: "いんでぃーじょーず" },
{ name: "Mr.スコップ", yomi: "みすたーすこっぷ" },
{ name: "ゾン・ビー・C", yomi: "ぞんびーちょっぱー" },
{ name: "ネコ2世", yomi: "ねこにせい" },
{ name: "クレクレパトラ", yomi: "くれくれぱとら" },
{ name: "ヤマトボケル", yomi: "やまとぼける" },
{ name: "エルドラゴーン", yomi: "えるどらごーん" },
{ name: "日ノ鳥", yomi: "ひのとり" },
{ name: "おがみ倒し", yomi: "おがみだおし" },
{ name: "キャプテンドード", yomi: "きゃぷてんどーど" },
{ name: "ちょうせんしゃ", yomi: "ちょうせんしゃ" },
{ name: "モリガミレックス", yomi: "もりがみれっくす" },
{ name: "ぷにじろう", yomi: "ぷにじろう" },
{ name: "しょうりん爺", yomi: "しょうりんじい" },
{ name: "らいせガール", yomi: "らいせがーる" },
{ name: "ふてくさる", yomi: "ふてくさる" },
{ name: "徳川マイゾウ", yomi: "とくがわまいぞう" },
{ name: "アレ・バッチーノ", yomi: "あればっちーの" },
{ name: "ガシャどくろT", yomi: "がしゃどくろとれじゃー" },
{ name: "カネクイヒメ", yomi: "かねくいひめ" },
{ name: "あきらMEN", yomi: "あきらめん" },
{ name: "思ウツボ", yomi: "おもうつぼ" },
{ name: "ドヤガリ族", yomi: "どやがりぞく" },
{ name: "ドヤ・オサ", yomi: "どやおさ" },
{ name: "バスコダ・ガマ", yomi: "ばすこだがま" },
{ name: "Cブシニャン", yomi: "くりすたるぶしにゃん" },
{ name: "TジバニャンG", yomi: "とれじゃーじばにゃんごーるど" },
{ name: "TコマさんG", yomi: "とれじゃーこまさんごーるど" },
{ name: "Dジバニャン", yomi: "どやがりじばにゃん" },
{ name: "Dコマさん", yomi: "どやがりこまさん" },
{ name: "インディ・JG", yomi: "いんでぃーじょーずごーるど" },
{ name: "Mr.スコップG", yomi: "みすたーすこっぷごーるど" },
{ name: "ゾン・ビー・CG", yomi: "ぞんびーちょっぱーごーるど" },
{ name: "ネコ2世G", yomi: "ねこにせいごーるど" },
{ name: "ヨーデルセン", yomi: "よーでるせん" },
{ name: "ナルシス2世", yomi: "なるしすにせい" },
{ name: "ザッパドキア", yomi: "ざっぱどきあ" },
{ name: "マドモアイゼル", yomi: "まどもあいぜる" },
{ name: "ロゼッタストーン", yomi: "ろぜったすとーん" },
{ name: "ドエスカリバー", yomi: "どえすかりばー" },
{ name: "アンコールデッド", yomi: "あんこーるでっど" },
{ name: "アーマーテラス", yomi: "あーまーてらす" },
{ name: "ダンドリー", yomi: "だんどりー" },
{ name: "スパット", yomi: "すぱっと" },
{ name: "タント", yomi: "たんと" },
{ name: "キレーネ", yomi: "きれーね" },
{ name: "トランカ", yomi: "とらんか" },
{ name: "キャトリーヌ", yomi: "きゃとりーぬ" },
{ name: "グスタフ", yomi: "ぐすたふ" },
{ name: "ゴーウィン", yomi: "ごーうぃん" },
{ name: "聖霊バンバラヤー", yomi: "せいれいばんばらやー" },
{ name: "闇エンマ", yomi: "やみえんま" },
{ name: "蛇王カイラ", yomi: "じゃおうかいら" },
{ name: "閻魔冥王マカ", yomi: "えんまめいおうまか" },
{ name: "閻魔猫王マタタビ", yomi: "えんまねこおうまたたび" },
{ name: "閻魔竜王ミズチ", yomi: "えんまりゅうおうみずち" },
{ name: "閻魔羅王テッカク", yomi: "えんまらおうてっかく" },
{ name: "不動明王", yomi: "ふどうみょうおう" },
  { name: "ジャー坊", yomi: "じゃーぼう" },
  { name: "しろく魔", yomi: "しろくま" },
  { name: "ハリー", yomi: "はりー" },
  { name: "ゴメンダコ", yomi: "ごめんだこ" },
  { name: "パックン", yomi: "ぱっくん" },
  { name: "キュンシー", yomi: "きゅんしー" },
  { name: "ハレ女", yomi: "はれおんな" },
  { name: "不動明王ボーイ", yomi: "ふどうみょうおうぼーい" },
  { name: "ホンマグロ大将", yomi: "ほんまぐろたいしょう" },
  { name: "セミコロン", yomi: "せみころん" },
  { name: "バンチョー", yomi: "ばんちょー" },
  { name: "フウくん", yomi: "ふうくん" },
  { name: "ライちゃん", yomi: "らいちゃん" },
  { name: "瓜坊", yomi: "うりぼう" },
  { name: "チャーリー", yomi: "ちゃーりー" },
  { name: "寸胴丸", yomi: "すんどうまる" },
  { name: "ジンタ", yomi: "じんた" },
  { name: "缶太郎", yomi: "かんたろう" },
  { name: "ジュニア", yomi: "じゅにあ" },
  { name: "ミッチー", yomi: "みっちー" },
  { name: "オグ・トグ・モグ", yomi: "おぐとぐもぐ" },
  { name: "洞潔", yomi: "どうけつ" },
  { name: "スーさん", yomi: "すーさん" },
  { name: "ヤマンバア", yomi: "やまんばあ" },
  { name: "タマモ", yomi: "たまも" },
  { name: "猫又", yomi: "ねこまた" },
  { name: "牛鬼", yomi: "ぎゅうき" },
  { name: "鳴釜", yomi: "なりがま" },
  { name: "ぬっぺふほふ", yomi: "ぬっぺふほふ" },
  { name: "フクロウ", yomi: "ふくろう" },
  { name: "朱夏", yomi: "しゅか" },
  { name: "空天", yomi: "くうてん" },
  { name: "イカカモネ議長", yomi: "いかかもねぎちょう" },
  { name: "ダニエル", yomi: "だにえる" },
  { name: "チョッキー", yomi: "ちょっきー" },
  { name: "いたしかたなし", yomi: "いたしかたなし"},
  { name: "紗夜", yomi: "さよ"},
  { name: "はむはむ", yomi: "はむはむ"},
  { name: "けずりん", yomi: "けずりん"},
  { name: "きぼりっクマ", yomi: "きぼりっくま"},
  { name: "べっちゃん", yomi: "べっちゃん"},
  { name: "玄冬", yomi: "げんとう"},
  { name: "白秋", yomi: "はくしゅう"},
  { name: "賢神アマテラス", yomi: "けんしんあまてらす"},
  { name: "ククリ姫", yomi: "くくりひめ"},
  { name: "月神ツクヨミ", yomi: "げっしんつくよみ"},
  { name: "かわうそ", yomi: "かわうそ"},
  { name: "小豆洗い", yomi: "あずきあらい"},
  { name: "紫炎", yomi: "しえん"},
  { name: "織田のぶニャが", yomi: "おだのぶにゃが"},
  { name: "天狐", yomi: "てんこ"}
];
